# Generated by Django 4.2.7 on 2024-03-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_temprerature_measurement_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='createad_at',
            new_name='created_at',
        ),
    ]
